# CNN - filters
## Multiple Filters
common convolutional layer은 32 to 512 filter를 학습한다.   
## Multiple Channels
이미지 channel은 depth를 의미한다.   
필터는 이미지의 채널과 같아야한다.   
3x3 filter 3x3x3(rows,cols,depth)   
필터 개수 만큼 layer들이 생성됨.   
## Multiple Layers

In [4]:
# 1d convolutions
from numpy import asarray
from keras.models import Sequential
from keras.layers import Conv1D
# define input data
# raw data
data = asarray([0, 0, 0, 1, 1, 0, 0, 0])
print(data.shape)
# keras 1D convolutional layer는 반드시 3D 여야 한다.
# raw data를 rows(n개 이미지),cols(이미지 특성들),channel(=depth)로 reshape함
data = data.reshape(1, 8, 1)
print(data.shape)
# create model
# 케라스에서 모델을 생성한다.
model = Sequential()
# 모델에 layer를 붙여준다.
# Conv1D(필터수, 커널사이즈(=필터사이즈), input사이즈)
model.add(Conv1D(1, 3, input_shape=(8, 1)))
# default weight는 랜덤으로 정해져 있다.
# define a vertical line detector
weights = [asarray([[[0]],[[1]],[[0]]]), asarray([0.0])]
# store the weights in the model
model.set_weights(weights)
# confirm they were stored
print(model.get_weights())
# apply filter to input data
yhat = model.predict(data)
print(yhat)
# manually apply a 1d filter
from numpy import asarray
print(asarray([0, 1, 0]).dot(asarray([0, 0, 0])))

(8,)
(1, 8, 1)
[array([[[0.]],

       [[1.]],

       [[0.]]], dtype=float32), array([0.], dtype=float32)]
[[[0.]
  [0.]
  [1.]
  [1.]
  [0.]
  [0.]]]
0


In [8]:
#2d convolutions
from numpy import asarray
from keras.models import Sequential
from keras.layers import Conv2D
# define input data ( 8x8 )
data = [[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 1, 0, 0],
		[0, 0, 0, 1, 0, 1, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0]]
# raw data를 복사한다.(원본이 변경되면 복사본 자동으로 변경됨)
data = asarray(data)
# keras 2D convolutional layer는 반드시 4D 여야 한다.
# raw data를 sampels(n개 이미지), rows,cols(이미지사이즈),channel(=depth)로 reshape함
data = data.reshape(1, 8, 8, 1)
# keras 모델 생성
model = Sequential()
# 모델에 layer를 붙여준다.
# Conv2D(필터수, 커널사이즈(=필터사이즈), (input사이즈,채널))
model.add(Conv2D(1, (3,3), input_shape=(8, 8, 1)))
# define a vertical line detector
detector = [[[[0]],[[1]],[[0]]],
            [[[0]],[[1]],[[0]]],
            [[[0]],[[1]],[[0]]]]
weights = [asarray(detector), asarray([0.0])]
# store the weights in the model
model.set_weights(weights)
# confirm they were stored
# data에 weight 적용 (weight와 dotproduct수행함)
print("weight",model.get_weights())
# apply filter to input data
# 학습한 모델을 초기 data에 적용시킨다.(=필터를 원래 data에 적용)
yhat = model.predict(data)
# 이는 원래 data와 weight(필터)를 dotproduct 한 결과와 같다.
print(yhat)
for r in range(yhat.shape[1]):
	# print each column in the row
	print([yhat[0,r,c,0] for c in range(yhat.shape[2])])

weight [array([[[[0.]],

        [[1.]],

        [[0.]]],


       [[[0.]],

        [[1.]],

        [[0.]]],


       [[[0.]],

        [[1.]],

        [[0.]]]], dtype=float32), array([0.], dtype=float32)]
[[[[0.]
   [0.]
   [3.]
   [3.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [3.]
   [3.]
   [1.]
   [0.]]

  [[0.]
   [0.]
   [3.]
   [2.]
   [2.]
   [0.]]

  [[0.]
   [0.]
   [3.]
   [2.]
   [2.]
   [0.]]

  [[0.]
   [0.]
   [3.]
   [2.]
   [1.]
   [0.]]

  [[0.]
   [0.]
   [3.]
   [3.]
   [0.]
   [0.]]]]
[0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
[0.0, 0.0, 3.0, 3.0, 1.0, 0.0]
[0.0, 0.0, 3.0, 2.0, 2.0, 0.0]
[0.0, 0.0, 3.0, 2.0, 2.0, 0.0]
[0.0, 0.0, 3.0, 2.0, 1.0, 0.0]
[0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
