In [3]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
import matplotlib.pyplot as plt
tf.disable_v2_behavior()
tf.__version__

'2.2.0'

In [7]:
# 특성 값들이 많아질 수록 코드가 더욱 복잡해진다. (사용 x)
x1_data = [73., 93., 89.]
x2_data = [80., 88., 91.]
x3_data = [75., 93., 90.]
# 목표로 하는 값
y_data = [152., 185., 180.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  46425.28 
Prediction:
 [-37.432148 -45.39058  -44.302227]
10 Cost:  1.9805316 
Prediction:
 [152.33438 182.61891 180.40025]
20 Cost:  1.6081444 
Prediction:
 [152.8627  183.26228 181.02982]
30 Cost:  1.6009511 
Prediction:
 [152.8603  183.26797 181.03093]
40 Cost:  1.5938104 
Prediction:
 [152.85641 183.27184 181.03026]
50 Cost:  1.5866743 
Prediction:
 [152.85254 183.27573 181.0296 ]
60 Cost:  1.5796217 
Prediction:
 [152.84866 183.27957 181.02896]
70 Cost:  1.5725971 
Prediction:
 [152.84483 183.28343 181.02832]
80 Cost:  1.5656003 
Prediction:
 [152.84097 183.28726 181.02766]
90 Cost:  1.5586871 
Prediction:
 [152.83716 183.29108 181.02704]
100 Cost:  1.5517746 
Prediction:
 [152.83333 183.29489 181.0264 ]
110 Cost:  1.5448884 
Prediction:
 [152.82953 183.2987  181.02574]
120 Cost:  1.5380582 
Prediction:
 [152.82571 183.30249 181.0251 ]
130 Cost:  1.531292 
Prediction:
 [152.82193 183.30626 181.02448]
140 Cost:  1.5245327 
Prediction:
 [152.81816 183.31003 181.02382]
150 C

1340 Cost:  0.9396269 
Prediction:
 [152.4349  183.69257 180.95935]
1350 Cost:  0.93624693 
Prediction:
 [152.43224 183.69524 180.95891]
1360 Cost:  0.9328802 
Prediction:
 [152.42957 183.69789 180.95845]
1370 Cost:  0.9295337 
Prediction:
 [152.42691 183.70056 180.95802]
1380 Cost:  0.9262133 
Prediction:
 [152.42426 183.7032  180.95758]
1390 Cost:  0.9229025 
Prediction:
 [152.4216  183.70584 180.95714]
1400 Cost:  0.91963595 
Prediction:
 [152.41898 183.70845 180.9567 ]
1410 Cost:  0.9163558 
Prediction:
 [152.41635 183.71107 180.95624]
1420 Cost:  0.9130849 
Prediction:
 [152.41373 183.7137  180.95578]
1430 Cost:  0.9098559 
Prediction:
 [152.4111  183.71631 180.95535]
1440 Cost:  0.9066532 
Prediction:
 [152.4085  183.7189  180.95493]
1450 Cost:  0.9034543 
Prediction:
 [152.4059  183.7215  180.95448]
1460 Cost:  0.90026444 
Prediction:
 [152.4033  183.72409 180.95404]
1470 Cost:  0.89708763 
Prediction:
 [152.40073 183.72668 180.9536 ]
1480 Cost:  0.89396924 
Prediction:
 [152.39

In [13]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


# None = n과 같다고 생각하기
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  692.2733 
Prediction:
 [[172.74664]
 [213.99467]
 [207.57588]
 [226.53236]
 [164.3069 ]]
10 Cost:  1.7245404 
Prediction:
 [[149.505  ]
 [186.05138]
 [180.04735]
 [196.55374]
 [142.99168]]
20 Cost:  1.7110593 
Prediction:
 [[149.43922]
 [185.96375]
 [179.96548]
 [196.46384]
 [142.92336]]
30 Cost:  1.7039543 
Prediction:
 [[149.44353]
 [185.9604 ]
 [179.96664]
 [196.46436]
 [142.9193 ]]
40 Cost:  1.6969 
Prediction:
 [[149.44803]
 [185.95734]
 [179.96805]
 [196.46513]
 [142.91547]]
50 Cost:  1.6898501 
Prediction:
 [[149.45256]
 [185.95428]
 [179.96948]
 [196.46594]
 [142.91165]]
60 Cost:  1.6828346 
Prediction:
 [[149.45705]
 [185.9512 ]
 [179.97087]
 [196.4667 ]
 [142.9078 ]]
70 Cost:  1.6758829 
Prediction:
 [[149.46153]
 [185.94817]
 [179.97229]
 [196.4675 ]
 [142.90402]]
80 Cost:  1.6689699 
Prediction:
 [[149.46599]
 [185.94513]
 [179.97368]
 [196.46829]
 [142.9002 ]]
90 Cost:  1.6620734 
Prediction:
 [[149.47046]
 [185.9421 ]
 [179.97508]
 [196.46907]
 [142.89644]]
100 C

1030 Cost:  1.1540148 
Prediction:
 [[149.84097]
 [185.69025]
 [180.09134]
 [196.53171]
 [142.5841 ]]
1040 Cost:  1.1498548 
Prediction:
 [[149.84445]
 [185.68791]
 [180.09245]
 [196.53227]
 [142.5812 ]]
1050 Cost:  1.1457185 
Prediction:
 [[149.8479 ]
 [185.68555]
 [180.09352]
 [196.53282]
 [142.57831]]
1060 Cost:  1.1416116 
Prediction:
 [[149.85135]
 [185.6832 ]
 [180.0946 ]
 [196.5334 ]
 [142.57544]]
1070 Cost:  1.1375121 
Prediction:
 [[149.85481]
 [185.6809 ]
 [180.0957 ]
 [196.53397]
 [142.57257]]
1080 Cost:  1.133439 
Prediction:
 [[149.85823]
 [185.67854]
 [180.09677]
 [196.5345 ]
 [142.56969]]
1090 Cost:  1.1293819 
Prediction:
 [[149.86166]
 [185.67621]
 [180.09785]
 [196.53506]
 [142.56683]]
1100 Cost:  1.125366 
Prediction:
 [[149.86507]
 [185.6739 ]
 [180.09892]
 [196.53561]
 [142.56398]]
1110 Cost:  1.1213475 
Prediction:
 [[149.86848]
 [185.67159]
 [180.1    ]
 [196.53616]
 [142.56114]]
1120 Cost:  1.1173686 
Prediction:
 [[149.87187]
 [185.66928]
 [180.10106]
 [196.536

In [19]:
import numpy as np
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(xy)
print(x_data)
print(y_data)
# Make sure the shape and data are OK
# print(x_data, "\nx_data shape:", x_data.shape)
# print(y_data, "\ny_data shape:", y_data.shape)

# data output
'''
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 ...
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 ...
 [149.]
 [192.]] 
y_data shape: (25, 1)
'''

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

[[ 73.  80.  75. 152.]
 [ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]
 [ 69.  74.  77. 149.]
 [ 47.  56.  60. 115.]
 [ 87.  79.  90. 175.]
 [ 79.  70.  88. 164.]
 [ 69.  70.  73. 141.]
 [ 70.  65.  74. 141.]
 [ 93.  95.  91. 184.]
 [ 79.  80.  73. 152.]
 [ 70.  73.  78. 148.]
 [ 93.  89.  96. 192.]
 [ 78.  75.  68. 147.]
 [ 81.  90.  93. 183.]
 [ 88.  92.  86. 177.]
 [ 78.  83.  77. 159.]
 [ 82.  86.  90. 177.]
 [ 86.  82.  89. 175.]
 [ 78.  83.  85. 175.]
 [ 76.  83.  71. 149.]
 [ 96.  93.  95. 192.]]
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83

200 Cost: 33.06429 
Prediction:
 [[147.66895 ]
 [190.03345 ]
 [180.81657 ]
 [197.42105 ]
 [147.46011 ]
 [110.593704]
 [144.71844 ]
 [102.7223  ]
 [180.93248 ]
 [169.56613 ]
 [142.6551  ]
 [146.27347 ]
 [186.63142 ]
 [155.24426 ]
 [147.28333 ]
 [192.10773 ]
 [151.14278 ]
 [171.23926 ]
 [175.91406 ]
 [156.04868 ]
 [171.47742 ]
 [177.84085 ]
 [162.28235 ]
 [148.32884 ]
 [194.84187 ]]
210 Cost: 32.923935 
Prediction:
 [[147.68419 ]
 [190.01923 ]
 [180.81921 ]
 [197.42514 ]
 [147.44019 ]
 [110.57704 ]
 [144.73242 ]
 [102.748886]
 [180.91306 ]
 [169.54785 ]
 [142.65762 ]
 [146.26204 ]
 [186.63235 ]
 [155.24106 ]
 [147.29262 ]
 [192.09741 ]
 [151.12819 ]
 [171.26436 ]
 [175.91977 ]
 [156.05753 ]
 [171.48871 ]
 [177.83075 ]
 [162.29553 ]
 [148.34023 ]
 [194.83163 ]]
220 Cost: 32.784348 
Prediction:
 [[147.6994  ]
 [190.005   ]
 [180.82187 ]
 [197.4292  ]
 [147.42029 ]
 [110.56041 ]
 [144.74637 ]
 [102.775406]
 [180.8937  ]
 [169.52966 ]
 [142.66014 ]
 [146.25064 ]
 [186.63326 ]
 [155.2379  ]
 

660 Cost: 27.322254 
Prediction:
 [[148.32329 ]
 [189.41725 ]
 [180.92761 ]
 [197.59814 ]
 [146.59515 ]
 [109.879036]
 [145.32855 ]
 [103.883644]
 [180.1     ]
 [168.79408 ]
 [142.76689 ]
 [145.78636 ]
 [186.66246 ]
 [155.09354 ]
 [147.69295 ]
 [191.66605 ]
 [150.49501 ]
 [172.33246 ]
 [176.15065 ]
 [156.42253 ]
 [171.97142 ]
 [177.40807 ]
 [162.85603 ]
 [148.80453 ]
 [194.39607 ]]
670 Cost: 27.212296 
Prediction:
 [[148.33649]
 [189.40468]
 [180.9298 ]
 [197.60176]
 [146.5775 ]
 [109.86462]
 [145.34111]
 [103.90753]
 [180.0832 ]
 [168.77875]
 [142.76921]
 [145.77661]
 [186.66289]
 [155.09016]
 [147.70145]
 [191.65712]
 [150.48146]
 [172.35489]
 [176.15524]
 [156.42995]
 [171.98161]
 [177.39934]
 [162.8678 ]
 [148.81384]
 [194.38692]]
680 Cost: 27.102957 
Prediction:
 [[148.34966 ]
 [189.39217 ]
 [180.93196 ]
 [197.60536 ]
 [146.55988 ]
 [109.85026 ]
 [145.3536  ]
 [103.931366]
 [180.06648 ]
 [168.76347 ]
 [142.77155 ]
 [145.76689 ]
 [186.66333 ]
 [155.0868  ]
 [147.70992 ]
 [191.64824

1150 Cost: 22.561857 
Prediction:
 [[148.92447]
 [188.84148]
 [181.02429]
 [197.76512]
 [145.78241]
 [109.22355]
 [145.90997]
 [104.99113]
 [179.33629]
 [168.10725]
 [142.87648]
 [145.34528]
 [186.67491]
 [154.92659]
 [148.08997]
 [191.261  ]
 [149.85751]
 [173.37051]
 [176.35257]
 [156.75508]
 [172.44481]
 [177.01189]
 [163.39969]
 [149.2172 ]
 [193.97325]]
1160 Cost: 22.476885 
Prediction:
 [[148.93582]
 [188.83054]
 [181.02606]
 [197.76834]
 [145.7669 ]
 [109.2112 ]
 [145.92117]
 [105.01244]
 [179.3219 ]
 [168.09451]
 [142.87863]
 [145.337  ]
 [186.67499]
 [154.92316]
 [148.09766]
 [191.25339]
 [149.84506]
 [173.39044]
 [176.35623]
 [156.76126]
 [172.45395]
 [177.00443]
 [163.41013]
 [149.22476]
 [193.96515]]
1170 Cost: 22.392372 
Prediction:
 [[148.94713 ]
 [188.81958 ]
 [181.02783 ]
 [197.77151 ]
 [145.7514  ]
 [109.198875]
 [145.93231 ]
 [105.0337  ]
 [179.30753 ]
 [168.08182 ]
 [142.88075 ]
 [145.32878 ]
 [186.67505 ]
 [154.91972 ]
 [148.10535 ]
 [191.24576 ]
 [149.83263 ]
 [173

1630 Cost: 18.945265 
Prediction:
 [[149.4317  ]
 [188.34773 ]
 [181.10144 ]
 [197.9096  ]
 [145.08168 ]
 [108.67146 ]
 [146.41797 ]
 [105.959305]
 [178.69289 ]
 [167.54651 ]
 [142.97472 ]
 [144.9785  ]
 [186.67209 ]
 [154.76205 ]
 [148.44217 ]
 [190.91995 ]
 [149.28438 ]
 [174.27444 ]
 [176.51013 ]
 [157.02658 ]
 [172.86052 ]
 [176.6789  ]
 [163.8722  ]
 [149.5451  ]
 [193.60556 ]]
1640 Cost: 18.879126 
Prediction:
 [[149.44151 ]
 [188.33812 ]
 [181.1029  ]
 [197.91245 ]
 [145.068   ]
 [108.660805]
 [146.42795 ]
 [105.97834 ]
 [178.68048 ]
 [167.53586 ]
 [142.97668 ]
 [144.97148 ]
 [186.6719  ]
 [154.75865 ]
 [148.44916 ]
 [190.91336 ]
 [149.27296 ]
 [174.29218 ]
 [176.51303 ]
 [157.03174 ]
 [172.86871 ]
 [176.67249 ]
 [163.88145 ]
 [149.55124 ]
 [193.59836 ]]
1650 Cost: 18.813328 
Prediction:
 [[149.45128 ]
 [188.32854 ]
 [181.10432 ]
 [197.91525 ]
 [145.05435 ]
 [108.650185]
 [146.43791 ]
 [105.997314]
 [178.6681  ]
 [167.52525 ]
 [142.97862 ]
 [144.96446 ]
 [186.6717  ]
 [154.75523

In [20]:
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

'''
Your score will be  [[185.33531]]
Other scores will be  [[178.36246]
 [177.03687]]
'''

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.
Instructions for updating:
Queue-base

330 Cost:  46.420506 
Prediction:
 [[152.00835]
 [189.50519]
 [183.40964]
 [197.46536]
 [148.08818]
 [106.42243]
 [142.48085]
 [ 97.98264]
 [175.87999]
 [158.45   ]]
340 Cost:  46.17775 
Prediction:
 [[152.00491]
 [189.49782]
 [183.40302]
 [197.47069]
 [148.07143]
 [106.42904]
 [142.50438]
 [ 98.02751]
 [175.88765]
 [158.48451]]
350 Cost:  45.936573 
Prediction:
 [[152.0015  ]
 [189.49043 ]
 [183.39641 ]
 [197.47595 ]
 [148.05467 ]
 [106.43557 ]
 [142.52782 ]
 [ 98.072235]
 [175.89523 ]
 [158.51881 ]]
360 Cost:  45.696945 
Prediction:
 [[151.99817 ]
 [189.48308 ]
 [183.38988 ]
 [197.48126 ]
 [148.03801 ]
 [106.44206 ]
 [142.55122 ]
 [ 98.116844]
 [175.9028  ]
 [158.55301 ]]
370 Cost:  45.45885 
Prediction:
 [[151.99484 ]
 [189.47572 ]
 [183.38333 ]
 [197.48654 ]
 [148.02132 ]
 [106.448494]
 [142.57452 ]
 [ 98.161316]
 [175.91026 ]
 [158.58699 ]]
380 Cost:  45.222237 
Prediction:
 [[151.99158]
 [189.46834]
 [183.37683]
 [197.49176]
 [148.00468]
 [106.45486]
 [142.59778]
 [ 98.20566]
 [1

820 Cost:  36.162804 
Prediction:
 [[151.88351]
 [189.14685]
 [183.11783]
 [197.70845]
 [147.30037]
 [106.68328]
 [143.55606]
 [100.03461]
 [176.18245]
 [159.95189]]
830 Cost:  35.984406 
Prediction:
 [[151.8818  ]
 [189.1396  ]
 [183.1125  ]
 [197.71306 ]
 [147.28499 ]
 [106.687386]
 [143.57643 ]
 [100.073524]
 [176.18718 ]
 [159.97882 ]]
840 Cost:  35.80715 
Prediction:
 [[151.88013 ]
 [189.13242 ]
 [183.10722 ]
 [197.71767 ]
 [147.26965 ]
 [106.691475]
 [143.59676 ]
 [100.11234 ]
 [176.19191 ]
 [160.00565 ]]
850 Cost:  35.630928 
Prediction:
 [[151.87846]
 [189.12517]
 [183.10194]
 [197.72224]
 [147.25432]
 [106.69548]
 [143.617  ]
 [100.15103]
 [176.19655]
 [160.03229]]
860 Cost:  35.45581 
Prediction:
 [[151.87683]
 [189.11797]
 [183.0967 ]
 [197.7268 ]
 [147.23903]
 [106.69947]
 [143.6372 ]
 [100.18962]
 [176.20116]
 [160.05882]]
870 Cost:  35.281765 
Prediction:
 [[151.87523 ]
 [189.11075 ]
 [183.09149 ]
 [197.73137 ]
 [147.22377 ]
 [106.703415]
 [143.65736 ]
 [100.228096]
 [176

1350 Cost:  28.054798 
Prediction:
 [[151.82938]
 [188.77069]
 [182.86636]
 [197.93533]
 [146.52303]
 [106.8469 ]
 [144.55847]
 [101.95079]
 [176.37083]
 [161.2059 ]]
1360 Cost:  27.925177 
Prediction:
 [[151.82901]
 [188.76376]
 [182.86217]
 [197.93932]
 [146.50908]
 [106.84903]
 [144.57594]
 [101.98424]
 [176.37326]
 [161.22646]]
1370 Cost:  27.796366 
Prediction:
 [[151.82864 ]
 [188.7568  ]
 [182.858   ]
 [197.94324 ]
 [146.49516 ]
 [106.851135]
 [144.59337 ]
 [102.01757 ]
 [176.37569 ]
 [161.24687 ]]
1380 Cost:  27.668299 
Prediction:
 [[151.82831 ]
 [188.7499  ]
 [182.85384 ]
 [197.94717 ]
 [146.48126 ]
 [106.853195]
 [144.61073 ]
 [102.05081 ]
 [176.37804 ]
 [161.2672  ]]
1390 Cost:  27.541035 
Prediction:
 [[151.828  ]
 [188.743  ]
 [182.84972]
 [197.95111]
 [146.46742]
 [106.85524]
 [144.62807]
 [102.08396]
 [176.38037]
 [161.28743]]
1400 Cost:  27.414438 
Prediction:
 [[151.8277  ]
 [188.73605 ]
 [182.84558 ]
 [197.955   ]
 [146.45357 ]
 [106.85724 ]
 [144.64534 ]
 [102.11700

1860 Cost:  22.322277 
Prediction:
 [[151.83394 ]
 [188.42569 ]
 [182.67444 ]
 [198.12346 ]
 [145.84508 ]
 [106.919266]
 [145.3887  ]
 [103.54042 ]
 [176.45259 ]
 [162.12854 ]]
1870 Cost:  22.225906 
Prediction:
 [[151.83446]
 [188.41913]
 [182.67108]
 [198.12688]
 [145.83246]
 [106.92004]
 [145.4038 ]
 [103.56936]
 [176.45341]
 [162.14429]]
1880 Cost:  22.130068 
Prediction:
 [[151.83499]
 [188.41255]
 [182.66774]
 [198.1303 ]
 [145.81985]
 [106.92076]
 [145.41885]
 [103.5982 ]
 [176.45421]
 [162.15994]]
1890 Cost:  22.034771 
Prediction:
 [[151.83554]
 [188.406  ]
 [182.66444]
 [198.13368]
 [145.80727]
 [106.92147]
 [145.43387]
 [103.62697]
 [176.455  ]
 [162.17554]]
1900 Cost:  21.940014 
Prediction:
 [[151.83609 ]
 [188.39944 ]
 [182.66113 ]
 [198.13708 ]
 [145.79471 ]
 [106.92216 ]
 [145.44882 ]
 [103.655655]
 [176.45573 ]
 [162.19104 ]]
1910 Cost:  21.845821 
Prediction:
 [[151.83669 ]
 [188.39293 ]
 [182.65785 ]
 [198.14047 ]
 [145.78218 ]
 [106.92284 ]
 [145.46376 ]
 [103.68426

'\nYour score will be  [[185.33531]]\nOther scores will be  [[178.36246]\n [177.03687]]\n'