In [1]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
import matplotlib.pyplot as plt
tf.disable_v2_behavior()
tf.__version__

Instructions for updating:
non-resource variables are not supported in the long term


'2.2.0'

In [3]:
# Training Data set
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]


X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
# Try to change learning_rate to small numbers
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))


0 7.2585707 [[-0.4078342  -0.26444432  0.7523052 ]
 [ 0.21089911 -0.12519048  0.27151522]
 [-0.8833627   0.5272891   0.78309405]]
1 4.127849 [[-0.38299    -0.26058567  0.72360235]
 [ 0.37305003 -0.05526839  0.03944223]
 [-0.7210602   0.60516036  0.5429203 ]]
2 3.2018106 [[-0.3582917  -0.3095289   0.74784726]
 [ 0.5347981  -0.25659144  0.07901728]
 [-0.5590238   0.41425705  0.5717872 ]]
3 2.3207269 [[-0.33462533 -0.31550744  0.73015946]
 [ 0.69281554 -0.23344757 -0.102144  ]
 [-0.39975178  0.44230393  0.38446832]]
4 1.5843976 [[-0.316382   -0.35526717  0.75167584]
 [ 0.8198252  -0.38681853 -0.07578266]
 [-0.26560584  0.2929231   0.39970317]]
5 1.2437701 [[-0.3222582  -0.3550045   0.75728935]
 [ 0.8069935  -0.33202147 -0.11774799]
 [-0.25591096  0.34493196  0.33799943]]
6 1.1913888 [[-0.32745138 -0.36793414  0.7754122 ]
 [ 0.7953162  -0.33729726 -0.10079492]
 [-0.24529189  0.33308175  0.33923057]]
7 1.1771916 [[-0.33258083 -0.37795603  0.7905635 ]
 [ 0.78437614 -0.32951894 -0.09763315]
 

In [8]:
import numpy as np

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)



0 Cost:  1544700800000.0 
Prediction:
 [[ -876824.1]
 [-1762947.1]
 [-1387293.2]
 [ -973110.9]
 [-1146492.6]
 [-1156125.2]
 [-1059785.9]
 [-1348744.4]]
1 Cost:  1.697132e+27 
Prediction:
 [[2.9059566e+13]
 [5.8499887e+13]
 [4.6019752e+13]
 [3.2259602e+13]
 [3.8019663e+13]
 [3.8339667e+13]
 [3.5139629e+13]
 [4.4739735e+13]]
2 Cost:  inf 
Prediction:
 [[-9.63218629e+20]
 [-1.93905789e+21]
 [-1.52538693e+21]
 [-1.06928804e+21]
 [-1.26021315e+21]
 [-1.27082011e+21]
 [-1.16475056e+21]
 [-1.48295908e+21]]
3 Cost:  inf 
Prediction:
 [[3.1927185e+28]
 [6.4272697e+28]
 [5.0561013e+28]
 [3.5443001e+28]
 [4.1771475e+28]
 [4.2123056e+28]
 [3.8607233e+28]
 [4.9154688e+28]]
4 Cost:  inf 
Prediction:
 [[-1.05826958e+36]
 [-2.13040536e+36]
 [-1.67591300e+36]
 [-1.17480605e+36]
 [-1.38457188e+36]
 [-1.39622555e+36]
 [-1.27968884e+36]
 [-1.62929832e+36]]
5 Cost:  inf 
Prediction:
 [[inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]]
6 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan

In [10]:
import numpy as np


def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)


xy = np.array(
    [
        [828.659973, 833.450012, 908100, 828.349976, 831.659973],
        [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
        [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
        [816, 820.958984, 1008100, 815.48999, 819.23999],
        [819.359985, 823, 1188100, 818.469971, 818.97998],
        [819, 823, 1198100, 816, 820.450012],
        [811.700012, 815.25, 1098100, 809.780029, 813.669983],
        [809.51001, 816.659973, 1398100, 804.539978, 809.559998],
    ]
)

# very important. It does not work without it.
xy = min_max_scaler(xy)
print(xy)

'''
[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
'''

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
train = tf.train.GradientDescentOptimizer(learning_rate=1e-5).minimize(cost)

# Launch the graph in a session.
with tf.Session() as sess:
    # Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer())

    for step in range(101):
        _, cost_val, hy_val = sess.run(
            [train, cost, hypothesis], feed_dict={X: x_data, Y: y_data}
        )
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
0 Cost:  3.1630816 
Prediction:
 [[2.9790847]
 [3.3338928]
 [2.6440837]
 [1.8158243]
 [2.3318493]
 [2.1413546]
 [1.3979485]
 [1.2270535]]
1 Cost:  3.162842 
Prediction:
 [[2.9789958]
 [3.333805 ]
 [2.6440105]
 [1.8157678]
 [2.3317823]
 [2.14129  ]
 [1.3979046]
 [1.22701  ]]
2 Cost:  3.1626024 
Prediction:
 [[2.9789069]
 [3.3337173]
 [2.6439376]
 [1.8157113]
 [2.3317156]
 [2.1412253]
 [1.3978606]
 [1.2269664]]
3 Cost:  3.1623626 
Prediction:
 [[2.9788177]
 [3.3336298]
 [2.6438646]
 [1.8156548]
 [2.3316488]
 [2.1411605]
 [1.3978168